import type { Publication, Category } from "@/types"

export const mockCategories: Category[] = [
  { id: 1, slug: "newspapers", name_ru: "Газеты", name_uz: "Gazetalar" },
  { id: 2, slug: "magazines", name_ru: "Журналы", name_uz: "Jurnallar" },
  { id: 3, slug: "business", name_ru: "Бизнес", name_uz: "Biznes" },
  { id: 4, slug: "science", name_ru: "Наука", name_uz: "Fan" },
  { id: 5, slug: "culture", name_ru: "Культура", name_uz: "Madaniyat" },
  { id: 6, slug: "kids", name_ru: "Детские", name_uz: "Bolalar" },
  { id: 7, slug: "sport", name_ru: "Спорт", name_uz: "Sport" },
]

const now = "2026-04-29T00:00:00Z"

export const mockPublications: Publication[] = [
  {
    id: 1,
    slug: "khalq-suzi",
    title_ru: "Народное слово",
    title_uz: "Xalq so'zi",
    description_ru: "Главная общественно-политическая газета страны.",
    description_uz: "Mamlakatning bosh ijtimoiy-siyosiy gazetasi.",
    cover_url: "",
    category_id: 1,
    type: "newspaper",
    price_per_month: 28000,
    is_published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 2,
    slug: "biznes-daily",
    title_ru: "Бизнес Daily",
    title_uz: "Biznes Daily",
    description_ru: "Деловые новости, аналитика рынков и финансов.",
    description_uz: "Biznes yangiliklari, bozor va moliyaviy tahlillar.",
    cover_url: "",
    category_id: 3,
    type: "newspaper",
    price_per_month: 45000,
    is_published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 3,
    slug: "fan-va-turmush",
    title_ru: "Наука и жизнь Узбекистана",
    title_uz: "Fan va Turmush",
    description_ru: "Научно-популярный журнал, исследования и открытия.",
    description_uz: "Ilmiy-ommabop jurnal, tadqiqotlar va kashfiyotlar.",
    cover_url: "",
    category_id: 4,
    type: "magazine",
    price_per_month: 38000,
    is_published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 4,
    slug: "sharq-yulduzi",
    title_ru: "Звезда Востока",
    title_uz: "Sharq Yulduzi",
    description_ru: "Литературно-художественный журнал, проза и поэзия.",
    description_uz: "Adabiy-badiiy jurnal, nasr va she'riyat.",
    cover_url: "",
    category_id: 5,
    type: "magazine",
    price_per_month: 32000,
    is_published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 5,
    slug: "sport-pres",
    title_ru: "Спорт Пресс",
    title_uz: "Sport Press",
    description_ru: "Футбол, кураш, бокс. Турниры и обзоры матчей.",
    description_uz: "Futbol, kurash, boks. Turnirlar va o'yin sharhlari.",
    cover_url: "",
    category_id: 7,
    type: "newspaper",
    price_per_month: 22000,
    is_published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 6,
    slug: "gulkhan",
    title_ru: "Гулхан",
    title_uz: "Gulxan",
    description_ru: "Журнал для детей и подростков, истории и игры.",
    description_uz: "Bolalar va o'smirlar uchun jurnal, hikoyalar va o'yinlar.",
    cover_url: "",
    category_id: 6,
    type: "magazine",
    price_per_month: 18000,
    is_published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 7,
    slug: "tashkent-times",
    title_ru: "Tashkent Times",
    title_uz: "Tashkent Times",
    description_ru: "Английская газета о жизни Ташкента и страны.",
    description_uz: "Toshkent va mamlakat hayoti haqida ingliz tilidagi gazeta.",
    cover_url: "",
    category_id: 1,
    type: "newspaper",
    price_per_month: 52000,
    is_published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 8,
    slug: "uz-economy",
    title_ru: "Экономика Узбекистана",
    title_uz: "O'zbekiston Iqtisodiyoti",
    description_ru: "Ежемесячный экономический журнал, статистика и прогнозы.",
    description_uz: "Oylik iqtisodiy jurnal, statistika va prognozlar.",
    cover_url: "",
    category_id: 3,
    type: "magazine",
    price_per_month: 65000,
    is_published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 9,
    slug: "madaniyat",
    title_ru: "Культура",
    title_uz: "Madaniyat",
    description_ru: "Театр, кино, выставки. Афиша и критика.",
    description_uz: "Teatr, kino, ko'rgazmalar. Afisha va tanqid.",
    cover_url: "",
    category_id: 5,
    type: "newspaper",
    price_per_month: 24000,
    is_published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 10,
    slug: "yosh-kuchlari",
    title_ru: "Молодые силы",
    title_uz: "Yosh Kuchlari",
    description_ru: "Молодёжная газета, образование и карьера.",
    description_uz: "Yoshlar gazetasi, ta'lim va karyera.",
    cover_url: "",
    category_id: 1,
    type: "newspaper",
    price_per_month: 19000,
    is_published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 11,
    slug: "tech-uz",
    title_ru: "Tech Uzbekistan",
    title_uz: "Tech Uzbekistan",
    description_ru: "Технологии, стартапы, цифровая экономика.",
    description_uz: "Texnologiyalar, startaplar, raqamli iqtisodiyot.",
    cover_url: "",
    category_id: 4,
    type: "magazine",
    price_per_month: 48000,
    is_published: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 12,
    slug: "saodat",
    title_ru: "Саодат",
    title_uz: "Saodat",
    description_ru: "Журнал для женщин, дом, мода, психология.",
    description_uz: "Ayollar uchun jurnal, uy, moda, psixologiya.",
    cover_url: "",
    category_id: 2,
    type: "magazine",
    price_per_month: 27000,
    is_published: true,
    created_at: now,
    updated_at: now,
  },
]
